/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (unauthenticated). */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the supplied bearer token. */
        get: operations["verifyAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List change events, newest first, cursor-paginated. */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/where/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace a commit/tag across builds, intents and per-env applies. */
        get: operations["where"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare what is deployed across two environments right now. */
        get: operations["diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize deploy activity since an instant (shift-handoff view). */
        get: operations["handoff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/around": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the changes in a window before an instant or an event. */
        get: operations["around"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report ingest health, source watermarks and unmapped events. */
        get: operations["doctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event counts over time (gap-filled), for the activity chart. */
        get: operations["statsActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/deploys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-environment deploy frequency, failures and health. */
        get: operations["statsDeploys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct env/service/actor values for filter dropdowns. */
        get: operations["facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services × environments current-deploy grid (diff visualized). */
        get: operations["matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The normalization rules and tag patterns in effect. */
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the inference rules (validated, persisted, hot-reloaded). */
        put: operations["putRules"];
        post?: never;
        /** Drop the rules override; revert to the YAML baseline. */
        delete: operations["resetRules"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tag_patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the tag patterns (validated, persisted, hot-reloaded). */
        put: operations["putTagPatterns"];
        post?: never;
        /** Drop the tag-patterns override; revert to the YAML baseline. */
        delete: operations["resetTagPatterns"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events: newly-stored events pushed live.
         * @description text/event-stream. Each `data:` frame is one Event (as in /events). Consume with fetch — EventSource cannot set the Authorization header.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Event: {
            /** @description ULID. */
            id: string;
            /**
             * Format: date-time
             * @description Source event time (UTC).
             */
            ts: string;
            /**
             * Format: date-time
             * @description When wtc stored it (UTC).
             */
            ingested_at: string;
            /** @enum {string} */
            source: "github" | "flux" | "helm" | "terraform" | "manual" | "generic" | "alertmanager";
            /** @enum {string} */
            kind: "build" | "merge" | "push" | "deploy" | "config_change" | "infra_change" | "rollback" | "alert" | "manual";
            /** @enum {string} */
            status: "started" | "succeeded" | "failed" | "unknown";
            /** @description Empty string means unmapped (surfaced by doctor). */
            env: string;
            cluster: string;
            namespace: string;
            service: string;
            actor: string;
            /** @description Git sha / revision. */
            ref: string;
            /** @description Primary artifact, e.g. registry/app:tag. */
            artifact: string;
            title: string;
            url: string;
            /** Format: int64 */
            duration_ms?: number | null;
            dedup_key: string;
            /** @description Redacted raw JSON; may be omitted. */
            payload?: string;
        };
        EventsResponse: {
            events: components["schemas"]["Event"][];
            /** @description Pass as ?cursor= to fetch the next page; absent on the last page. */
            next_cursor?: string;
        };
        WhereEnv: {
            env: string;
            /** @description Merge/push that targeted this env. */
            intent?: components["schemas"]["Event"] | null;
            /** @description Latest deploy carrying the change. */
            applied?: components["schemas"]["Event"] | null;
            /**
             * Format: int64
             * @description applied.ts - intent.ts.
             */
            lag_ms?: number | null;
            /** @description Explicit gaps, never guessed. */
            unknown?: string[];
        };
        WhereReport: {
            input: string;
            /** @description Longest known form of the resolved sha. */
            sha: string;
            builds: components["schemas"]["Event"][];
            intents: components["schemas"]["Event"][];
            envs: components["schemas"]["WhereEnv"][];
            notes?: string[];
        };
        DiffRow: {
            service: string;
            /** @description Artifact (fallback ref) in env A; empty = not deployed. */
            a: string;
            /** @description Same for env B. */
            b: string;
            /** Format: date-time */
            a_ts?: string | null;
            /** Format: date-time */
            b_ts?: string | null;
            /**
             * Format: int64
             * @description |aTS - bTS| when both exist and differ.
             */
            drift_seconds?: number | null;
            last_actor?: string;
            in_sync: boolean;
            /** @description Env name when deployed to exactly one side. */
            only_in?: string;
            /** @description Compared refs because artifact data was missing. */
            revision_only: boolean;
        };
        DiffReport: {
            env_a: string;
            env_b: string;
            rows: components["schemas"]["DiffRow"][];
        };
        EnvStats: {
            total: number;
            failed: number;
        };
        ActorCount: {
            actor: string;
            count: number;
        };
        HandoffReport: {
            /** Format: date-time */
            since: string;
            deploys_by_env: {
                [key: string]: components["schemas"]["EnvStats"];
            };
            /** @description Failed deploys in window. */
            failures?: components["schemas"]["Event"][];
            infra_changes: number;
            rollbacks: number;
            unmapped: number;
            top_actors?: components["schemas"]["ActorCount"][];
            /** @description First ever seen inside the window. */
            new_services?: string[];
        };
        SourceHealth: {
            source: string;
            count_24h: number;
            /** Format: date-time */
            last_ts: string;
        };
        PollState: {
            repo: string;
            resource: string;
            /** Format: date-time */
            watermark: string;
            /** Format: date-time */
            updated_at: string;
        };
        DoctorReport: {
            /** Format: int64 */
            total_events: number;
            /** Format: int64 */
            db_size_bytes: number;
            /**
             * Format: date-time
             * @description Absent on an empty ledger.
             */
            oldest_event?: string | null;
            sources: components["schemas"]["SourceHealth"][];
            unmapped_24h: number;
            unmapped_samples?: string[];
            clock_skew_24h: number;
            poll?: components["schemas"]["PollState"][];
        };
        ActivityBucket: {
            /** @description Bucket start (UTC): YYYY-MM-DD for day, YYYY-MM-DDThh:00 for hour. */
            ts: string;
            total: number;
            succeeded: number;
            failed: number;
        };
        ActivityStats: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @enum {string} */
            bucket: "day" | "hour";
            /** @description Contiguous (gap-filled) oldest-first. */
            buckets: components["schemas"]["ActivityBucket"][];
        };
        EnvDeployStats: {
            env: string;
            /** @description Deploy events in the window. */
            total: number;
            succeeded: number;
            failed: number;
            /** @description Distinct services deployed. */
            services: number;
            /**
             * Format: date-time
             * @description Most recent deploy in the window.
             */
            last_ts?: string | null;
            /** @description Status of the most recent deploy (env-health signal). */
            last_status?: string;
        };
        DeployStats: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @description Non-empty envs only, sorted by name. */
            envs: components["schemas"]["EnvDeployStats"][];
        };
        Facets: {
            envs: string[];
            services: string[];
            actors: string[];
        };
        MatrixCell: {
            /** @description Deploy event id, for deep-linking. */
            id: string;
            ref?: string;
            artifact?: string;
            /** Format: date-time */
            ts: string;
        };
        MatrixRow: {
            service: string;
            /** @description Keyed by env; a missing env means not deployed there. */
            cells: {
                [key: string]: components["schemas"]["MatrixCell"];
            };
        };
        Matrix: {
            /** @description Column order as requested. */
            envs: string[];
            services: components["schemas"]["MatrixRow"][];
        };
        /** @description Selector; empty fields are unconstrained. Strings support * and ** globs. */
        RuleMatch: {
            source?: string;
            repo?: string;
            branch?: string;
            event?: string;
            workflow?: string;
            cluster?: string;
            object_kind?: string;
            paths?: string[];
        };
        /** @description Fields a rule sets. Values are Go templates over the fact map. */
        RuleSet: {
            env?: string;
            cluster?: string;
            namespace?: string;
            service?: string;
            kind?: string;
            actor?: string;
        };
        Rule: {
            match: components["schemas"]["RuleMatch"];
            set: components["schemas"]["RuleSet"];
        };
        ConfigResponse: {
            rules: components["schemas"]["Rule"][];
            tag_patterns: string[];
            /** @description true when rules come from a DB override rather than the YAML baseline. */
            rules_overridden: boolean;
            tag_patterns_overridden: boolean;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    verifyAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                env?: string;
                service?: string;
                kind?: string;
                status?: string;
                /** @description Exact actor match (facet). */
                actor?: string;
                /** @description Full-text search over event text. */
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                /** @description Opaque cursor from a prior response's next_cursor. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    where: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A git sha (short or long), image tag, or artifact ref. */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change's journey. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhereReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    diff: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-service comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    handoff: {
        parameters: {
            query?: {
                /** @description Defaults to 7 days ago. */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    around: {
        parameters: {
            query?: {
                /** @description Anchor instant. One of ts or id is required. */
                ts?: string;
                /** @description Anchor on an event id (e.g. an alert). One of ts or id is required. */
                id?: string;
                /** @description Lookback duration (Go format, e.g. 30m). Default 30m. */
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events preceding the anchor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    doctor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    statsActivity: {
        parameters: {
            query?: {
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
                /** @description Time granularity. Default day. */
                bucket?: "day" | "hour";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contiguous count series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    statsDeploys: {
        parameters: {
            query?: {
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-env deploy summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    facets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sorted distinct dimension values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    matrix: {
        parameters: {
            query?: {
                /** @description Ordered comma-separated column list. Omitted => distinct non-ephemeral envs. */
                envs?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current-deploy grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current rules + tag patterns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rules: components["schemas"]["Rule"][];
                };
            };
        };
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resetRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putTagPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_patterns: string[];
                };
            };
        };
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resetTagPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of Event frames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
