/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (unauthenticated). */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the supplied bearer token. */
        get: operations["verifyAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The server's build-stamped version (bearer-authed — versions fingerprint deployments). */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List change events, newest first, cursor-paginated. */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/where/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace a commit/tag across builds, intents and per-env applies. */
        get: operations["where"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare what is deployed across two environments, current or as of a past instant. */
        get: operations["diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize deploy activity since an instant (shift-handoff view). */
        get: operations["handoff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/around": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the changes in a window before an instant or an event. */
        get: operations["around"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank the changes most likely to have caused an alert (or list the alerts following a change).
         * @description Anchored on an alert event or a bare instant, scores the changes in the preceding window as suspects — a deterministic documented heuristic: recency, same env (hard signal), same service, kind weight, failed/degraded bump. Anchored on a non-alert change the direction flips: it lists the alerts that fired in the window after it.
         */
        get: operations["blast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report which rule set each inferred field of an event.
         * @description Replays the CURRENT rules (DB overrides included) over the event's recorded ingest-time facts with a first-writer-wins trace: per field, the winning rule (index + match spec), 'normalizer' when the source parser pre-filled it, or 'unmatched'. Rows without recorded facts (pre-migration, or generic/record/wrap sources) report facts_recorded=false — never a guess.
         */
        get: operations["explain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream the filtered ledger as CSV, NDJSON or a JSON array.
         * @description Audit/compliance export — 'every prod change in Q3'. Filters mirror /events; ordering is ts DESC. CSV carries the flat columns in a stable append-only order; ndjson and json carry full events including payload and facts. Streams page-by-page, so large ranges never buffer server-side.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a consistent snapshot of the sqlite ledger.
         * @description A point-in-time VACUUM INTO snapshot taken while serving (WAL-safe, compacted), streamed as a sqlite database file. The postgres backend answers 501 — back it up with pg_dump instead (docs/setup/backup.md).
         */
        get: operations["backup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report ingest health, source watermarks and unmapped events. */
        get: operations["doctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event counts over time (gap-filled), for the activity chart. */
        get: operations["statsActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/deploys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-environment deploy frequency, failures and health. */
        get: operations["statsDeploys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Change-failure rate and MTTR over a window (overall, per env, per owner). */
        get: operations["dora"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logical changes in a window: build → merge → per-env deploys collapsed by app sha. */
        get: operations["changesets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct env/service/actor values for filter dropdowns. */
        get: operations["facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services × environments deploy grid (diff visualized), current or as of a past instant. */
        get: operations["matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The normalization rules and tag patterns in effect. */
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the inference rules (validated, persisted, hot-reloaded). */
        put: operations["putRules"];
        post?: never;
        /** Drop the rules override; revert to the YAML baseline. */
        delete: operations["resetRules"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tag_patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the tag patterns (validated, persisted, hot-reloaded). */
        put: operations["putTagPatterns"];
        post?: never;
        /** Drop the tag-patterns override; revert to the YAML baseline. */
        delete: operations["resetTagPatterns"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events: newly-stored events pushed live.
         * @description text/event-stream. Each `data:` frame is one Event (as in /events). Consume with fetch — EventSource cannot set the Authorization header.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Event: {
            /** @description ULID. */
            id: string;
            /**
             * Format: date-time
             * @description Source event time (UTC).
             */
            ts: string;
            /**
             * Format: date-time
             * @description When wtc stored it (UTC).
             */
            ingested_at: string;
            /** @enum {string} */
            source: "github" | "flux" | "argocd" | "helm" | "terraform" | "manual" | "generic" | "alertmanager";
            /** @enum {string} */
            kind: "build" | "merge" | "push" | "deploy" | "config_change" | "infra_change" | "rollback" | "alert" | "manual";
            /** @enum {string} */
            status: "started" | "succeeded" | "failed" | "degraded" | "unknown";
            /** @description Empty string means unmapped (surfaced by doctor). */
            env: string;
            cluster: string;
            namespace: string;
            service: string;
            /** @description Source repo (owner/name); empty for cluster-side events (flux/argo). */
            repo: string;
            /** @description Owning team, inferred from service via the catalog; empty when unmapped. */
            owner: string;
            actor: string;
            /** @description Git sha / revision. */
            ref: string;
            /** @description Primary artifact, e.g. registry/app:tag. */
            artifact: string;
            title: string;
            url: string;
            /** Format: int64 */
            duration_ms?: number | null;
            dedup_key: string;
            /** @description Redacted raw JSON; may be omitted. */
            payload?: string;
            /** @description Redacted ingest-time rule facts + pre-rules snapshot (JSON, for /explain); absent when not recorded. */
            facts?: string;
        };
        EventsResponse: {
            events: components["schemas"]["Event"][];
            /** @description Pass as ?cursor= to fetch the next page; absent on the last page. */
            next_cursor?: string;
        };
        BlastSuspect: {
            event: components["schemas"]["Event"];
            /** @description Deterministic suspicion score; higher = likelier. Relative within one report. */
            score: number;
            /** @description Human-readable score breakdown (recency, same env/service, kind, status). */
            reasons: string[];
        };
        BlastReport: {
            anchor?: components["schemas"]["Event"];
            /** Format: date-time */
            anchor_ts: string;
            /**
             * @description causes: changes before an alert/instant. effects: alerts after a change.
             * @enum {string}
             */
            direction: "causes" | "effects";
            /** @description Env used for the same-env signal; absent when unknown (signal disabled, noted). */
            env?: string;
            /** @description Service used for the same-service signal. */
            service?: string;
            /** Format: int64 */
            window_ms: number;
            /** @description Ranked best-first. Always an array, never null. */
            suspects: components["schemas"]["BlastSuspect"][];
            /** @description Explicit caveats — disabled signals, truncation, empty windows. */
            notes?: string[];
        };
        FieldTrace: {
            /** @description env | cluster | namespace | service | kind | actor. */
            field: string;
            value?: string;
            /**
             * @description rule: a rules-engine entry set it. normalizer: the source parser pre-filled it. unmatched: nothing set it.
             * @enum {string}
             */
            origin: "rule" | "normalizer" | "unmatched";
            /** @description Zero-based index into the effective rules list; present when origin=rule. */
            rule_index?: number;
            /** @description Compact match spec of the winning rule, e.g. 'source=flux namespace=prod-*'. */
            rule_match?: string;
        };
        ExplainReport: {
            event_id: string;
            title: string;
            source: string;
            /** @description False for rows ingested before the facts migration or via sources that set fields directly; traces are then absent. */
            facts_recorded: boolean;
            facts?: components["schemas"]["RuleFacts"];
            traces?: components["schemas"]["FieldTrace"][];
            /** @description Caveats — unrecorded facts, rules drift since ingest. */
            notes?: string[];
        };
        /** @description The ingest-time facts the rules engine matched against (recorded, redacted). */
        RuleFacts: {
            source?: string;
            repo?: string;
            branch?: string;
            event?: string;
            workflow?: string;
            actor?: string;
            cluster?: string;
            object_kind?: string;
            object_name?: string;
            namespace?: string;
            reason?: string;
            project?: string;
            dest_server?: string;
            source_path?: string;
            env_label?: string;
            paths?: string[];
            paths_truncated?: boolean;
        };
        WhereEnv: {
            env: string;
            /** @description Merge/push that targeted this env. */
            intent?: components["schemas"]["Event"] | null;
            /** @description Latest deploy carrying the change. */
            applied?: components["schemas"]["Event"] | null;
            /**
             * Format: int64
             * @description applied.ts - intent.ts.
             */
            lag_ms?: number | null;
            /** @description Explicit gaps, never guessed. */
            unknown?: string[];
        };
        WhereReport: {
            input: string;
            /** @description Longest known form of the resolved sha. */
            sha: string;
            builds: components["schemas"]["Event"][];
            intents: components["schemas"]["Event"][];
            envs: components["schemas"]["WhereEnv"][];
            notes?: string[];
        };
        DiffRow: {
            service: string;
            /** @description Artifact (fallback ref) in env A; empty = not deployed. */
            a: string;
            /** @description Same for env B. */
            b: string;
            /** Format: date-time */
            a_ts?: string | null;
            /** Format: date-time */
            b_ts?: string | null;
            /**
             * Format: int64
             * @description |aTS - bTS| when both exist and differ.
             */
            drift_seconds?: number | null;
            last_actor?: string;
            in_sync: boolean;
            /** @description Env name when deployed to exactly one side. */
            only_in?: string;
            /** @description Compared refs because artifact data was missing. */
            revision_only: boolean;
        };
        DiffReport: {
            env_a: string;
            env_b: string;
            rows: components["schemas"]["DiffRow"][];
        };
        EnvStats: {
            total: number;
            failed: number;
        };
        ActorCount: {
            actor: string;
            count: number;
        };
        HandoffReport: {
            /** Format: date-time */
            since: string;
            deploys_by_env: {
                [key: string]: components["schemas"]["EnvStats"];
            };
            /** @description Failed deploys in window. */
            failures?: components["schemas"]["Event"][];
            infra_changes: number;
            rollbacks: number;
            unmapped: number;
            top_actors?: components["schemas"]["ActorCount"][];
            /** @description First ever seen inside the window. */
            new_services?: string[];
        };
        SourceHealth: {
            source: string;
            count_24h: number;
            /** Format: date-time */
            last_ts: string;
        };
        PollState: {
            repo: string;
            resource: string;
            /** Format: date-time */
            watermark: string;
            /** Format: date-time */
            updated_at: string;
        };
        DoctorReport: {
            /** Format: int64 */
            total_events: number;
            /** Format: int64 */
            db_size_bytes: number;
            /**
             * Format: date-time
             * @description Absent on an empty ledger.
             */
            oldest_event?: string | null;
            sources: components["schemas"]["SourceHealth"][];
            unmapped_24h: number;
            unmapped_samples?: string[];
            /** @description Services absent from the catalog; only when a catalog is in use. */
            unowned_services?: string[];
            clock_skew_24h: number;
            poll?: components["schemas"]["PollState"][];
            /** @description Mapping-webhook sources with a probable unstable dedup_key. */
            webhook_churn?: components["schemas"]["WebhookChurn"][];
            /** @description Recent per-source mapping-template eval failures. */
            webhook_mapping_errors?: components["schemas"]["WebhookMappingError"][];
        };
        WebhookChurn: {
            source: string;
            title: string;
            rows: number;
            window_s: number;
        };
        WebhookMappingError: {
            source: string;
            count: number;
            last_error: string;
            /** Format: date-time */
            last_at: string;
        };
        ActivityBucket: {
            /** @description Bucket start (UTC): YYYY-MM-DD for day, YYYY-MM-DDThh:00 for hour. */
            ts: string;
            total: number;
            succeeded: number;
            failed: number;
        };
        ActivityStats: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @enum {string} */
            bucket: "day" | "hour";
            /** @description Contiguous (gap-filled) oldest-first. */
            buckets: components["schemas"]["ActivityBucket"][];
        };
        EnvDeployStats: {
            env: string;
            /** @description Deploy events in the window. */
            total: number;
            succeeded: number;
            failed: number;
            /** @description Distinct services deployed. */
            services: number;
            /**
             * Format: date-time
             * @description Most recent deploy in the window.
             */
            last_ts?: string | null;
            /** @description Status of the most recent deploy (env-health signal). */
            last_status?: string;
        };
        DeployStats: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @description Non-empty envs only, sorted by name. */
            envs: components["schemas"]["EnvDeployStats"][];
        };
        DORAMetrics: {
            /** @description Terminal deploy events (succeeded + failed). */
            deploys: number;
            /** @description Deploys that failed or were followed by an alert/rollback in the same env within the window. */
            failures: number;
            /** @description failures / deploys; 0 when no deploys. */
            change_failure_rate: number;
            /** @description Resolved alerts counted for MTTR. */
            incidents: number;
            /** @description Mean alert firing→resolved duration; absent when no incident resolved. */
            mttr_seconds?: number;
        };
        DORAGroup: components["schemas"]["DORAMetrics"] & {
            /** @description The env or owner name. */
            key: string;
        };
        DORAReport: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @description Deploy→failure attribution window. */
            window_seconds: number;
            overall: components["schemas"]["DORAMetrics"];
            by_env: components["schemas"]["DORAGroup"][];
            by_owner: components["schemas"]["DORAGroup"][];
        };
        Changeset: {
            /** @description Longest known form of the app commit sha. */
            sha: string;
            /** @description Representative title (merge > build > other). */
            title: string;
            services: string[];
            /** @description Envs with a succeeded deploy of this sha. */
            envs: string[];
            owners: string[];
            repos: string[];
            actors: string[];
            kinds: string[];
            /** @description Every ref in the change; filters the timeline to exactly its events. */
            refs: string[];
            /** Format: date-time */
            first_ts: string;
            /** Format: date-time */
            last_ts: string;
            /** @description Events folded into the changeset. */
            events: number;
            /** @description Any failed/degraded event. */
            failed: boolean;
            /** @description Any succeeded deploy. */
            deployed: boolean;
        };
        ChangesetsReport: {
            /** Format: date-time */
            since: string;
            /** Format: date-time */
            until: string;
            /** @description Newest-first by most recent event. */
            changesets: components["schemas"]["Changeset"][];
        };
        Facets: {
            sources: string[];
            envs: string[];
            services: string[];
            repos: string[];
            owners: string[];
            actors: string[];
        };
        MatrixCell: {
            /** @description Deploy event id, for deep-linking. */
            id: string;
            ref?: string;
            artifact?: string;
            /** Format: date-time */
            ts: string;
        };
        MatrixRow: {
            service: string;
            /** @description Keyed by env; a missing env means not deployed there. */
            cells: {
                [key: string]: components["schemas"]["MatrixCell"];
            };
        };
        Matrix: {
            /** @description Column order as requested. */
            envs: string[];
            services: components["schemas"]["MatrixRow"][];
        };
        /** @description Selector; empty fields are unconstrained. Strings support * and ** globs. */
        RuleMatch: {
            source?: string;
            repo?: string;
            branch?: string;
            event?: string;
            workflow?: string;
            cluster?: string;
            object_kind?: string;
            paths?: string[];
        };
        /** @description Fields a rule sets. Values are Go templates over the fact map. */
        RuleSet: {
            env?: string;
            cluster?: string;
            namespace?: string;
            service?: string;
            kind?: string;
            actor?: string;
        };
        Rule: {
            match: components["schemas"]["RuleMatch"];
            set: components["schemas"]["RuleSet"];
        };
        VersionResponse: {
            /** @description Build-stamped binary version ("dev" for unstamped builds). */
            version: string;
        };
        /** @description Constant "********" when the secret is configured, "" when not. Never the value, never a partial, length-independent. */
        MaskedSecret: string;
        /** @description Serve daemon surface (redacted). */
        ConfigServer: {
            listen: string;
            cors_origins: string[];
            /** @description Raw ingest bodies are being written to disk (dev capture mode) — surface as a warning. */
            capture_enabled: boolean;
        };
        /** @description Storage backend; for postgres the DSN's location parts with credentials stripped (absent when the DSN does not parse). */
        ConfigStorage: {
            /** @enum {string} */
            backend: "sqlite" | "postgres";
            dsn: components["schemas"]["MaskedSecret"];
            host?: string;
            port?: number;
            database?: string;
        };
        ConfigAuth: {
            /** @description One mask per configured token — count visible, values never. */
            api_tokens: components["schemas"]["MaskedSecret"][];
        };
        ConfigGitHub: {
            webhook_secret: components["schemas"]["MaskedSecret"];
            api_token: components["schemas"]["MaskedSecret"];
            poll_interval: string;
            poller_enabled: boolean;
            /** @description Poller scope; empty with poller_enabled means auto-discovery. Entries may be globs. */
            repos: string[];
            infra_path: string;
            /** @description First-poll history window, e.g. "1d", "7d". */
            backfill: string;
        };
        ConfigGitLab: {
            base_url: string;
            webhook_secret: components["schemas"]["MaskedSecret"];
            api_token: components["schemas"]["MaskedSecret"];
            poll_interval: string;
            poller_enabled: boolean;
            projects: string[];
            infra_path: string;
            /** @description First-poll history window. */
            backfill: string;
        };
        /** @description Ingest allow/deny selector; empty fields are unconstrained, string fields are globs (* one segment, ** any depth). */
        ConfigScopeMatch: {
            namespace?: string;
            /** @description Flux involvedObject.name / Argo app name. */
            object_name?: string;
            object_kind?: string;
            /** @description Flux only. */
            cluster?: string;
            /** @description ArgoCD only. */
            project?: string;
        };
        /** @description Ingest allow/deny lists. Deny wins over allow; empty allow = allow all; empty deny = deny none. */
        ConfigScope: {
            allow: components["schemas"]["ConfigScopeMatch"][];
            deny: components["schemas"]["ConfigScopeMatch"][];
        };
        ConfigFlux: {
            hmac_key: components["schemas"]["MaskedSecret"];
            suppression_window: string;
            scope: components["schemas"]["ConfigScope"];
        };
        ConfigArgoCD: {
            webhook_secret: components["schemas"]["MaskedSecret"];
            suppression_window: string;
            scope: components["schemas"]["ConfigScope"];
        };
        ConfigWebhookAuth: {
            /** @enum {string} */
            mode: "token" | "hmac";
            header?: string;
            algo?: string;
            prefix?: string;
            secret: components["schemas"]["MaskedSecret"];
        };
        /** @description One mapping webhook: auth shape with the secret masked, templates in full. */
        ConfigWebhook: {
            name: string;
            preset?: string;
            auth: components["schemas"]["ConfigWebhookAuth"];
            dedup_key: string;
            /** @description Effective (preset-resolved) field templates, shown in full. */
            mapping: {
                [key: string]: string;
            };
            facts?: {
                [key: string]: string;
            };
        };
        ConfigSources: {
            github: components["schemas"]["ConfigGitHub"];
            gitlab: components["schemas"]["ConfigGitLab"];
            flux: components["schemas"]["ConfigFlux"];
            argocd: components["schemas"]["ConfigArgoCD"];
            webhooks: components["schemas"]["ConfigWebhook"][];
        };
        ConfigDigest: {
            enabled: boolean;
            interval: string;
            window: string;
            slack_webhook: components["schemas"]["MaskedSecret"];
        };
        ConfigRetention: {
            enabled: boolean;
            keep: string;
            ephemeral_env_pattern?: string;
            ephemeral_keep?: string;
            interval?: string;
        };
        ConfigMetrics: {
            /** @description Separate unauthenticated /metrics listener address; "" = not open. */
            listen: string;
        };
        /** @description Effective config: live-editable normalization (rules/tag_patterns) plus the redacted static snapshot of server/storage/auth/sources/jobs. Secrets are constant "********" masks — values never leave the server. */
        ConfigResponse: {
            server: components["schemas"]["ConfigServer"];
            storage: components["schemas"]["ConfigStorage"];
            auth: components["schemas"]["ConfigAuth"];
            sources: components["schemas"]["ConfigSources"];
            digest: components["schemas"]["ConfigDigest"];
            retention: components["schemas"]["ConfigRetention"];
            metrics: components["schemas"]["ConfigMetrics"];
            rules: components["schemas"]["Rule"][];
            tag_patterns: string[];
            /** @description true when rules come from a DB override rather than the YAML baseline. */
            rules_overridden: boolean;
            tag_patterns_overridden: boolean;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    verifyAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Facet OR-set (comma-separated): github/gitlab/flux/argocd/… or mapping-webhook names. */
                source?: string;
                /** @description Facet OR-set (comma-separated). */
                env?: string;
                /** @description Facet OR-set (comma-separated). */
                service?: string;
                /** @description Facet OR-set (comma-separated): source repo (owner/name). */
                repo?: string;
                /** @description Facet OR-set (comma-separated): owning team. */
                owner?: string;
                /** @description Facet OR-set (comma-separated). */
                kind?: string;
                /** @description Facet OR-set (comma-separated). */
                status?: string;
                /** @description Facet OR-set (comma-separated). */
                actor?: string;
                /** @description Exact git sha/revision OR-set (comma-separated) — used to scope the timeline to one changeset. */
                ref?: string;
                /** @description Full-text search over event text. */
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                /** @description Opaque cursor from a prior response's next_cursor. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    where: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A git sha (short or long), image tag, or artifact ref. */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change's journey. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhereReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    diff: {
        parameters: {
            query: {
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                a: string;
                b: string;
                /** @description Point-in-time: reconstruct the comparison as of this RFC3339 instant. Omitted => current state. */
                at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-service comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    handoff: {
        parameters: {
            query?: {
                /** @description Defaults to 7 days ago. */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    around: {
        parameters: {
            query?: {
                /** @description Anchor instant. One of ts or id is required. */
                ts?: string;
                /** @description Anchor on an event id (e.g. an alert). One of ts or id is required. */
                id?: string;
                /** @description Lookback duration (Go format, e.g. 30m). Default 30m. */
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events preceding the anchor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    blast: {
        parameters: {
            query?: {
                /** @description Anchor instant. One of ts or id is required. */
                ts?: string;
                /** @description Anchor on an event id (an alert for causes; a change for effects). One of ts or id is required. */
                id?: string;
                /** @description Scoring env context; overrides the anchor event's env. Required with a bare ts anchor to enable the same-env signal. */
                env?: string;
                /** @description Scoring service context; overrides the anchor event's service. */
                service?: string;
                /** @description Lookback (causes) / lookahead (effects) duration (Go format, e.g. 2h). Default 2h. */
                window?: string;
                /** @description Maximum suspects returned. Default 20, capped at 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked suspects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlastReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    explain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inference trace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    export: {
        parameters: {
            query?: {
                /** @description Source(s), comma-separated. */
                source?: string;
                /** @description Env(s), comma-separated. */
                env?: string;
                /** @description Service(s), comma-separated. */
                service?: string;
                /** @description Repo(s), comma-separated. */
                repo?: string;
                /** @description Kind(s), comma-separated. */
                kind?: string;
                /** @description Status(es), comma-separated. */
                status?: string;
                /** @description Actor(s), comma-separated. */
                actor?: string;
                /** @description Free-text search over title/service/actor/artifact. */
                q?: string;
                /** @description Window start. */
                since?: string;
                /** @description Window end. */
                until?: string;
                /** @description csv (default), ndjson or json. */
                format?: "csv" | "ndjson" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The export stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/x-ndjson": string;
                    "application/json": components["schemas"]["Event"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    backup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sqlite snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not supported by the postgres backend. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    doctor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    statsActivity: {
        parameters: {
            query?: {
                /** @description Scope facet OR-set (comma-separated). */
                env?: string;
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
                /** @description Time granularity. Default day. */
                bucket?: "day" | "hour";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contiguous count series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    statsDeploys: {
        parameters: {
            query?: {
                /** @description Scope facet OR-set (comma-separated). */
                env?: string;
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-env deploy summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    dora: {
        parameters: {
            query?: {
                /** @description Scope facet OR-set (comma-separated). */
                env?: string;
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
                /** @description Deploy→failure attribution span (Go duration, e.g. 60m). Default 1h. */
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deploy-quality metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DORAReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changesets: {
        parameters: {
            query?: {
                /** @description Scope facet OR-set (comma-separated). */
                env?: string;
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                /** @description Window start. Default 30 days ago. */
                since?: string;
                /** @description Window end. Default now. */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changesets, newest-first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetsReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    facets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sorted distinct dimension values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    matrix: {
        parameters: {
            query?: {
                /** @description Scope facet OR-set (comma-separated). */
                service?: string;
                /** @description Scope facet OR-set (comma-separated). */
                owner?: string;
                /** @description Ordered comma-separated column list. Omitted => distinct non-ephemeral envs. */
                envs?: string;
                /** @description Point-in-time: reconstruct the grid as of this RFC3339 instant. Omitted => current state. */
                at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deploy grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current rules + tag patterns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rules: components["schemas"]["Rule"][];
                };
            };
        };
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resetRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putTagPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_patterns: string[];
                };
            };
        };
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resetTagPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New effective config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream of Event frames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
