---
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: false
  version: 0.4.0
  version_files:
  - .cz.yaml:version
  - deploy/helm/wtc/Chart.yaml:appVersion
  version_scheme: semver
