commitizen:
  name: cz_conventional_commits
  version: 0.4.0
  tag_format: demo-web-v$version
  bump_message: "bump(demo-web): $current_version -> $new_version [skip ci]"
  version_files:
    - .cz.yaml:version
